### ISSUE TITLE
Host manrajsingh.in on gh-pages

### ISSUE THREAD

**Issue by bogas04** [manrajgrover/manrajgrover.github.io#1]
I see that you have your homepage on manrajsingh.in and also have this github.io page (which isn't updated).

You could push the source of manrajsingh.in here (if it's a static) and point this repo to manrajsingh.in domain. This would not only ensure lower hosting charges (gh-pages is free after all), but possibly lower down-times, better perf etc.

**Comment by manrajgrover** [comment]
I was actually thinking about hosting some of my projects. I might shift to AWS soon. Yes, I'm yet to update the github.io page. Thanks for bringing it up though.

**Comment by manrajgrover** [comment]
@bogas04 This is fixed. I'll move the code later. http://manrajsingh.in/

**Comment by manrajgrover** [comment]
Website migrated to repository
